import test from "node:test";
import assert from "node:assert/strict";
import { updateAccountConnectionInQueryData } from "./account-connection-api.ts";

test("updateAccountConnectionInQueryData marks the targeted account connected", () => {
  const result = updateAccountConnectionInQueryData(
    {
      success: true,
      accounts: [
        {
          id: "acc-1",
          userId: "user-1",
          name: "Follower One",
          platform: "Rithmic",
          accountType: "follower",
          tradovateUsername: null,
          tradovateAccountId: null,
          tradovateEnvironment: null,
          tradeifyUsername: null,
          tradeifyAccountId: null,
          tradeifyApiKey: null,
          rithmicUsername: "rit-user",
          rithmicAccountId: "rit-1",
          rithmicPassword: "secret",
          rithmicEnvironment: "test",
          rithmicSystemName: "Rithmic Test",
          apiKey: null,
          apiSecret: null,
          isConnected: false,
          balance: null,
          openPositions: 0,
          pnl: "0",
          riskMode: "global",
          positionScaling: 100,
          copySizingMode: "MULTIPLIER",
          fixedQuantity: null,
          reverseCopying: false,
          maxContracts: null,
          maxOpenPositions: null,
          allowedDirections: "both",
          maxDailyLoss: null,
          maxDailyLossPct: null,
          maxWeeklyLoss: null,
          maxWeeklyLossPct: null,
          maxDrawdownPct: null,
          maxConsecutiveLosses: null,
          blockedTickers: null,
          allowedTickers: null,
          maxTradesPerDay: null,
          minAccountBalance: null,
          tradingStartTime: null,
          tradingEndTime: null,
          tradingDays: null,
          cooldownAfterLoss: null,
          onBreachAction: "pause",
          lastSync: null,
        },
      ],
    },
    "acc-1",
    true,
  );

  assert.equal(result?.accounts[0].isConnected, true);
});

test("updateAccountConnectionInQueryData leaves other accounts unchanged", () => {
  const result = updateAccountConnectionInQueryData(
    {
      success: true,
      accounts: [
        {
          id: "acc-1",
          userId: "user-1",
          name: "One",
          platform: "Rithmic",
          accountType: "follower",
          tradovateUsername: null,
          tradovateAccountId: null,
          tradovateEnvironment: null,
          tradeifyUsername: null,
          tradeifyAccountId: null,
          tradeifyApiKey: null,
          rithmicUsername: null,
          rithmicAccountId: null,
          rithmicPassword: null,
          rithmicEnvironment: null,
          rithmicSystemName: null,
          apiKey: null,
          apiSecret: null,
          isConnected: false,
          balance: null,
          openPositions: 0,
          pnl: "0",
          riskMode: "global",
          positionScaling: 100,
          copySizingMode: "MULTIPLIER",
          fixedQuantity: null,
          reverseCopying: false,
          maxContracts: null,
          maxOpenPositions: null,
          allowedDirections: "both",
          maxDailyLoss: null,
          maxDailyLossPct: null,
          maxWeeklyLoss: null,
          maxWeeklyLossPct: null,
          maxDrawdownPct: null,
          maxConsecutiveLosses: null,
          blockedTickers: null,
          allowedTickers: null,
          maxTradesPerDay: null,
          minAccountBalance: null,
          tradingStartTime: null,
          tradingEndTime: null,
          tradingDays: null,
          cooldownAfterLoss: null,
          onBreachAction: "pause",
          lastSync: null,
        },
        {
          id: "acc-2",
          userId: "user-1",
          name: "Two",
          platform: "Tradovate",
          accountType: "master",
          tradovateUsername: "tv",
          tradovateAccountId: "tv-1",
          tradovateEnvironment: "demo",
          tradeifyUsername: null,
          tradeifyAccountId: null,
          tradeifyApiKey: null,
          rithmicUsername: null,
          rithmicAccountId: null,
          rithmicPassword: null,
          rithmicEnvironment: null,
          rithmicSystemName: null,
          apiKey: null,
          apiSecret: null,
          isConnected: false,
          balance: null,
          openPositions: 0,
          pnl: "0",
          riskMode: "global",
          positionScaling: 100,
          copySizingMode: "MULTIPLIER",
          fixedQuantity: null,
          reverseCopying: false,
          maxContracts: null,
          maxOpenPositions: null,
          allowedDirections: "both",
          maxDailyLoss: null,
          maxDailyLossPct: null,
          maxWeeklyLoss: null,
          maxWeeklyLossPct: null,
          maxDrawdownPct: null,
          maxConsecutiveLosses: null,
          blockedTickers: null,
          allowedTickers: null,
          maxTradesPerDay: null,
          minAccountBalance: null,
          tradingStartTime: null,
          tradingEndTime: null,
          tradingDays: null,
          cooldownAfterLoss: null,
          onBreachAction: "pause",
          lastSync: null,
        },
      ],
    },
    "acc-1",
    true,
  );

  assert.equal(result?.accounts[0].isConnected, true);
  assert.equal(result?.accounts[1].isConnected, false);
});
