ALTER TABLE "accounts"
  ADD COLUMN IF NOT EXISTS "copy_sizing_mode" text DEFAULT 'MULTIPLIER',
  ADD COLUMN IF NOT EXISTS "fixed_quantity" integer,
  ADD COLUMN IF NOT EXISTS "reverse_copying" boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS "max_contracts" integer,
  ADD COLUMN IF NOT EXISTS "max_open_positions" integer,
  ADD COLUMN IF NOT EXISTS "allowed_directions" text DEFAULT 'both',
  ADD COLUMN IF NOT EXISTS "max_daily_loss" numeric(12, 2),
  ADD COLUMN IF NOT EXISTS "max_daily_loss_pct" numeric(5, 2),
  ADD COLUMN IF NOT EXISTS "max_weekly_loss" numeric(12, 2),
  ADD COLUMN IF NOT EXISTS "max_weekly_loss_pct" numeric(5, 2),
  ADD COLUMN IF NOT EXISTS "max_drawdown_pct" numeric(5, 2),
  ADD COLUMN IF NOT EXISTS "max_consecutive_losses" integer,
  ADD COLUMN IF NOT EXISTS "blocked_tickers" text[],
  ADD COLUMN IF NOT EXISTS "allowed_tickers" text[],
  ADD COLUMN IF NOT EXISTS "max_trades_per_day" integer,
  ADD COLUMN IF NOT EXISTS "min_account_balance" numeric(12, 2),
  ADD COLUMN IF NOT EXISTS "trading_start_time" text,
  ADD COLUMN IF NOT EXISTS "trading_end_time" text,
  ADD COLUMN IF NOT EXISTS "trading_days" text[],
  ADD COLUMN IF NOT EXISTS "cooldown_after_loss" integer,
  ADD COLUMN IF NOT EXISTS "on_breach_action" text DEFAULT 'pause';
