import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

test("accounts page surfaces shared position sync review state", () => {
  const source = readFileSync("client/src/pages/accounts.tsx", "utf8");

  assert.match(source, /\/api\/position-sync\/reviews/);
  assert.match(source, /toPositionSyncWorkflowState\(positionSyncWorkflowData\.reviews\)/);
  assert.match(source, /useAccountsPagePreferences/);
  assert.match(source, /useAccountsPositionSyncReview/);
  assert.match(source, /savePositionSyncWorkflowMutation/);
  assert.match(source, /onWorkflowSaved: refreshAccountsRuntimeOverviewQuery/);
  assert.match(source, /onWorkflowSaveSuccess: \(count\) =>/);
  assert.match(source, /buildPositionSyncWorkflowKey\(group\.groupId, follower\.followerAccountId\)/);
  assert.match(source, /Approved/);
  assert.match(source, /Handed Off/);
  assert.match(source, /Completed Manually/);
  assert.match(source, /Reviewed/);
  assert.match(source, /Simulated/);
  assert.match(source, /Shared sync review note/);
  assert.match(source, /Optional ownership or handoff reason/);
  assert.match(source, /handleApprovePositionSyncEntry/);
  assert.match(source, /handleTakePositionSyncOwnership/);
  assert.match(source, /handleHandOffPositionSyncEntry/);
  assert.match(source, /handleCompletePositionSyncEntry/);
  assert.match(source, /Approve/);
  assert.match(source, /Take ownership/);
  assert.match(source, /Hand off/);
  assert.match(source, /Mark completed manually/);
  assert.match(source, /follower\.repairRecommendation/);
  assert.match(source, /follower\.repairRecommendation\.label/);
  assert.match(source, /follower\.repairRecommendation\.reason/);
  assert.match(source, /follower\.repairRecommendation\.complexityLabel/);
  assert.match(source, /describePositionSyncSimulationGuidance/);
  assert.match(source, /Review note:/);
  assert.match(source, /Operator owner:/);
  assert.match(source, /Ownership changes:/);
  assert.match(source, /Latest ownership reason:/);
  assert.match(source, /Ownership Timeline/);
  assert.match(source, /Approved on/);
  assert.match(source, /Handed off on/);
  assert.match(source, /Completed manually on/);
  assert.match(source, /workflowEntry\?\.status !== 'simulated'/);
  assert.match(source, /workflowEntry\?\.status !== 'approved'/);
  assert.match(source, /workflowEntry\?\.status !== 'handed_off'/);
  assert.match(source, /No broker orders submitted/);
});
