import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

test("activity page summarizes shared position sync review counts", () => {
  const source = readFileSync("client/src/pages/activity.tsx", "utf8");

  assert.match(source, /usePositionSyncReviewData/);
  assert.match(source, /useOperatorFollowUpData/);
  assert.match(source, /ActivitySyncRepairBoard/);
  assert.match(source, /ActivityCopyGroupAlertBoard/);
  assert.match(source, /ActivityCopyGroupHealthBoard/);
  assert.match(source, /ActivityExecutionFollowUpBoard/);
  assert.match(source, /ActivityRiskFollowUpBoard/);
  assert.match(source, /ActivitySyncReviewBoard/);
  assert.match(source, /useActivitySyncRepairBoard/);
  assert.match(source, /useActivitySyncReviewBoard/);
  assert.match(source, /"\/api\/runtime\/accounts-overview"/);
  assert.match(source, /"\/api\/runtime\/dashboard-overview"/);
  assert.match(source, /useFollowUpReviewData/);
  assert.match(source, /buildPositionSyncQueue\(/);
  assert.match(source, /buildOperatorWorkSummary\(/);
  assert.match(source, /riskFollowUpSummary/);
  assert.match(source, /executionFollowUpSummary/);
  assert.match(source, /appendRiskFollowUpOperatorAssignment/);
  assert.match(source, /reviewedSyncCount/);
  assert.match(source, /simulatedSyncCount/);
  assert.match(source, /approvedSyncCount/);
  assert.match(source, /handedOffSyncCount/);
  assert.match(source, /completedManuallySyncCount/);
  assert.match(source, /operatorWorkSummary/);
  assert.match(source, /repairCandidateNotes/);
  assert.match(source, /handleOpenRepairCandidateInQueue/);
  assert.match(source, /positionSyncRepairBoardSummary/);
  assert.match(source, /savePositionSyncWorkflow:\s*\(reviews\) => savePositionSyncWorkflowMutation\.mutate\(reviews\)/);
  assert.match(source, /simulatePositionSync:\s*\(targets\) => simulatePositionSyncMutation\.mutate\(targets\)/);
  assert.match(source, /positionSyncRepairCandidates/);
  assert.match(source, /filteredRepairCandidates/);
  assert.match(source, /selectedRepairCandidateKeys/);
  assert.match(source, /handleToggleRepairCandidateSelection/);
  assert.match(source, /handleSelectAllVisibleRepairCandidates/);
  assert.match(source, /handleSelectAutoReadyRepairCandidates/);
  assert.match(source, /handleClearRepairCandidateSelection/);
  assert.match(source, /handleBulkReviewRepairCandidates/);
  assert.match(source, /handleBulkSimulateRepairCandidates/);
  assert.match(source, /handleBulkTakeRepairCandidateOwnership/);
  assert.match(source, /handleBulkApproveRepairCandidates/);
  assert.match(source, /handleSaveRepairCandidateNote/);
  assert.match(source, /onRepairCandidateNoteChange=\{\(key, value\) =>/);
  assert.match(source, /onOpenInQueue=\{\(entry\) =>/);
  assert.match(source, /handleOpenRepairCandidateInQueue\(\{/);
  assert.match(source, /note: repairCandidateNotes\[entry\.key\]\?\.trim\(\) \|\| positionSyncWorkflowState\[entry\.key\]\?\.note/);
  assert.match(source, /Sync Reviews/);
  assert.match(source, /Alert Stories/);
  assert.match(source, /"\/api\/copy-groups\/alerts"/);
  assert.match(source, /copyGroupAlertStories/);
  assert.match(source, /recentCopyGroupAlerts/);
  assert.match(source, /"\/api\/copy-groups\/alert-reviews"/);
  assert.match(source, /copyGroupAlertReviewsData/);
  assert.match(source, /copyGroupAlertReviewsByStoryKey/);
  assert.match(source, /copyGroupAlertNotes/);
  assert.match(source, /copyGroupAlertFilter/);
  assert.match(source, /copyGroupAlertSearch/);
  assert.match(source, /selectedCopyGroupAlertStoryKeys/);
  assert.match(source, /filteredCopyGroupAlertStories/);
  assert.match(source, /sortedCopyGroupAlertStories/);
  assert.match(source, /unownedCopyGroupAlertCount/);
  assert.match(source, /myCopyGroupAlertCount/);
  assert.match(source, /reviewedCopyGroupAlertCount/);
  assert.match(source, /staleCopyGroupAlertCount/);
  assert.match(source, /newCopyGroupAlertCount/);
  assert.match(source, /isCopyGroupAlertReviewStale/);
  assert.match(source, /getCopyGroupAlertFreshnessLabel/);
  assert.match(source, /saveCopyGroupAlertReviewsMutation/);
  assert.match(source, /buildCopyGroupAlertReviewPayload/);
  assert.match(source, /handleTakeCopyGroupAlertOwnership/);
  assert.match(source, /handleAcknowledgeCopyGroupAlert/);
  assert.match(source, /handleReopenCopyGroupAlert/);
  assert.match(source, /handleToggleCopyGroupAlertSelection/);
  assert.match(source, /handleSelectAllVisibleCopyGroupAlerts/);
  assert.match(source, /handleSelectUnownedCopyGroupAlerts/);
  assert.match(source, /handleClearCopyGroupAlertSelection/);
  assert.match(source, /handleBulkTakeCopyGroupAlertOwnership/);
  assert.match(source, /handleBulkAcknowledgeCopyGroupAlerts/);
  assert.match(source, /New alert/);
  assert.match(source, /Retriggered after review/);
  assert.match(source, /Covered by review/);
  assert.match(source, /Owned and pending/);
  assert.match(source, /Shared Operator Work/);
  assert.match(source, /Ownership Gaps/);
  assert.match(source, /buildCopyGroupHealthWatchlist/);
  assert.match(source, /describeCopyGroupPulse/);
  assert.match(source, /summarizeCopyGroups/);
  assert.match(source, /activityByGroupId/);
  assert.match(source, /useActivityCopyGroupHealthBoard/);
  assert.match(source, /saveActivityPreferences:\s*\(settings\) => saveActivityPreferencesMutation\.mutate\(settings\)/);
  assert.match(source, /copyGroupHealthReviews/);
  assert.match(source, /copyGroupHealthNotes/);
  assert.match(source, /buildCopyGroupHealthConcernSignature/);
  assert.match(source, /countRecentMatchingHealthReviews/);
  assert.match(source, /copyGroupHealthReviewFilter/);
  assert.match(source, /copyGroupHealthRecoveryFilter/);
  assert.match(source, /copyGroupHealthBoardView/);
  assert.match(source, /copyGroupHealthSearch/);
  assert.match(source, /copyGroupHealthBulkResultSummary/);
  assert.match(source, /selectedCopyGroupHealthGroupIds/);
  assert.match(source, /setCopyGroupHealthSearch/);
  assert.match(source, /setCopyGroupHealthReviewFilter/);
  assert.match(source, /setCopyGroupHealthRecoveryFilter/);
  assert.match(source, /setCopyGroupHealthBoardView/);
  assert.match(source, /staleCopyGroupHealthReviewCount/);
  assert.match(source, /unreviewedCopyGroupHealthCount/);
  assert.match(source, /recurringCopyGroupHealthCount/);
  assert.match(source, /recoverNowCopyGroupHealthCount/);
  assert.match(source, /recoverNowCopyGroupHealthEntries/);
  assert.match(source, /stabilizeSoonCopyGroupHealthCount/);
  assert.match(source, /resumeCheckCopyGroupHealthCount/);
  assert.match(source, /stageBeforeUseCopyGroupHealthCount/);
  assert.match(source, /sortedCopyGroupHealthEntries/);
  assert.match(source, /riskFollowUpSearch/);
  assert.match(source, /riskFollowUpFilter/);
  assert.match(source, /filteredRiskFollowUpItems/);
  assert.match(source, /reviewedRiskFollowUpCount/);
  assert.match(source, /ownedRiskFollowUpCount/);
  assert.match(source, /unownedRiskFollowUpCount/);
  assert.match(source, /reassignedRiskFollowUpCount/);
  assert.match(source, /selectedRiskFollowUpAccountIds/);
  assert.match(source, /handleToggleRiskFollowUpSelection/);
  assert.match(source, /handleSelectAllVisibleRiskFollowUpItems/);
  assert.match(source, /handleSelectUnownedRiskFollowUpItems/);
  assert.match(source, /handleClearRiskFollowUpSelection/);
  assert.match(source, /handleBulkTakeRiskFollowUpOwnership/);
  assert.match(source, /handleBulkMarkRiskFollowUpReviewed/);
  assert.match(source, /handleBulkReopenRiskFollowUpItems/);
  assert.match(source, /handleTakeRiskFollowUpOwnership/);
  assert.match(source, /handleSaveRiskFollowUpNote/);
  assert.match(source, /handleMarkRiskFollowUpReviewed/);
  assert.match(source, /handleReopenRiskFollowUpItem/);
  assert.match(source, /saveRiskFollowUpReviewsMutation/);
  assert.match(source, /executionFollowUpSearch/);
  assert.match(source, /executionFollowUpFilter/);
  assert.match(source, /filteredExecutionFollowUpItems/);
  assert.match(source, /reviewedExecutionFollowUpCount/);
  assert.match(source, /failedExecutionFollowUpCount/);
  assert.match(source, /staleExecutionFollowUpCount/);
  assert.match(source, /partialExecutionFollowUpCount/);
  assert.match(source, /activeExecutionFollowUpCount/);
  assert.match(source, /selectedExecutionFollowUpHistoryIds/);
  assert.match(source, /handleToggleExecutionFollowUpSelection/);
  assert.match(source, /handleSelectAllVisibleExecutionFollowUpItems/);
  assert.match(source, /handleSelectFailedExecutionFollowUpItems/);
  assert.match(source, /handleClearExecutionFollowUpSelection/);
  assert.match(source, /handleExecutionFollowUpRecheck/);
  assert.match(source, /handleExecutionFollowUpReview/);
  assert.match(source, /handleReopenExecutionFollowUpItem/);
  assert.match(source, /handleBulkRecheckExecutionFollowUpItems/);
  assert.match(source, /handleBulkReviewExecutionFollowUpItems/);
  assert.match(source, /handleBulkTakeExecutionFollowUpOwnership/);
  assert.match(source, /handleBulkReopenExecutionFollowUpItems/);
  assert.match(source, /handleTakeExecutionFollowUpOwnership/);
  assert.match(source, /handleSaveExecutionFollowUpNote/);
  assert.match(source, /appendExecutionFollowUpOperatorAssignment/);
  assert.match(source, /recheckExecutionFollowUpItemMutation/);
  assert.match(source, /saveExecutionFollowUpReviewsMutation/);
  assert.match(source, /ActivityOperatorAuditBoard/);
  assert.match(source, /overdueSyncEntries/);
  assert.match(source, /unassignedSyncEntries/);
  assert.match(source, /reassignedSyncEntries/);
  assert.match(source, /queueAuditFocus/);
  assert.match(source, /queueSort/);
  assert.match(source, /saveActivityPreferencesMutation/);
  assert.match(source, /apiRequest\("PATCH", "\/api\/user\/settings", settings\)/);
  assert.match(source, /copyGroupHealthReviewFilter/);
  assert.match(source, /copyGroupHealthReviewsJson/);
  assert.match(source, /queryClient\.setQueryData\(\["\/api\/auth\/me"\], result\)/);
  assert.match(source, /handleSelectAuditFocus/);
  assert.match(source, /queueAuditFocus={queueAuditFocus}/);
  assert.match(source, /overdueSyncEntries={overdueSyncEntries}/);
  assert.match(source, /unassignedSyncEntries={unassignedSyncEntries}/);
  assert.match(source, /reassignedSyncEntries={reassignedSyncEntries}/);
  assert.match(source, /onSelectAuditFocus={handleSelectAuditFocus}/);
  assert.match(source, /sortedAuditFocusedQueue/);
  assert.match(source, /syncQueueBoardView/);
  assert.match(source, /onQueueSearchChange={setQueueSearch}/);
  assert.match(source, /onSyncQueueBoardViewChange={setSyncQueueBoardView}/);
  assert.match(source, /onQueueSortChange={setQueueSort}/);
  assert.match(source, /onClearQueueAuditFocus=\{\(\) => setQueueAuditFocus\("all"\)\}/);
  assert.match(source, /onQueueFilterChange={setQueueFilter}/);
  assert.match(source, /assignmentReasons={assignmentReasons}/);
  assert.match(source, /getPositionSyncStatusLabel={getPositionSyncStatusLabel}/);
  assert.match(source, /getPositionSyncStatusTone={getPositionSyncStatusTone}/);
  assert.match(source, /getPositionSyncStatusTimestamp={getPositionSyncStatusTimestamp}/);
  assert.match(source, /onAssignmentReasonChange=\{\(key, value\) =>/);
  assert.match(source, /onApprove={handleApproveSyncQueueEntry}/);
  assert.match(source, /onTakeOwnership={handleTakeOwnership}/);
  assert.match(source, /onHandOff={handleHandOffSyncQueueEntry}/);
  assert.match(source, /onComplete={handleCompleteSyncQueueEntry}/);
});
