import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

test("activity page summarizes shared position sync review counts", () => {
  const source = readFileSync("client/src/pages/activity.tsx", "utf8");

  assert.match(source, /"\/api\/position-sync\/reviews"/);
  assert.match(source, /"\/api\/position-sync\/plans"/);
  assert.match(source, /"\/api\/runtime\/accounts-overview"/);
  assert.match(source, /"\/api\/risk-follow-up\/reviews"/);
  assert.match(source, /toPositionSyncWorkflowState\(positionSyncWorkflowData\.reviews\)/);
  assert.match(source, /buildPositionSyncQueue\(/);
  assert.match(source, /filterPositionSyncQueue\(/);
  assert.match(source, /buildAccountRiskFollowUpQueue\(/);
  assert.match(source, /buildRiskNotificationFollowUpQueue\(/);
  assert.match(source, /appendRiskFollowUpOperatorAssignment/);
  assert.match(source, /reviewedSyncCount/);
  assert.match(source, /simulatedSyncCount/);
  assert.match(source, /approvedSyncCount/);
  assert.match(source, /handedOffSyncCount/);
  assert.match(source, /completedManuallySyncCount/);
  assert.match(source, /attentionSyncCount/);
  assert.match(source, /unassignedSyncCount/);
  assert.match(source, /Sync Reviews/);
  assert.match(source, /Needs Follow-Up/);
  assert.match(source, /Unassigned Follow-Up/);
  assert.match(source, /Copy Group Health/);
  assert.match(source, /Operational watchlist/);
  assert.match(source, /buildCopyGroupHealthWatchlist/);
  assert.match(source, /describeCopyGroupPulse/);
  assert.match(source, /summarizeCopyGroups/);
  assert.match(source, /Needs Attention/);
  assert.match(source, /On Watch/);
  assert.match(source, /Reviewed/);
  assert.match(source, /Stale Reviews/);
  assert.match(source, /Recurring Groups/);
  assert.match(source, /Followers Offline/);
  assert.match(source, /Latest recovery action:/);
  assert.match(source, /lastStableSignalLabel/);
  assert.match(source, /Time in current warning state:/);
  assert.match(source, /activityByGroupId/);
  assert.match(source, /COPY_GROUP_HEALTH_REVIEW_STORAGE_KEY/);
  assert.match(source, /loadCopyGroupHealthReviews/);
  assert.match(source, /copyGroupHealthReviews/);
  assert.match(source, /copyGroupHealthNotes/);
  assert.match(source, /copyGroupHealthPreferencesHydrated/);
  assert.match(source, /normalizeCopyGroupHealthReviewFilter/);
  assert.match(source, /parseCopyGroupHealthReviewsJson/);
  assert.match(source, /user\.copyGroupHealthReviewFilter/);
  assert.match(source, /user\.copyGroupHealthReviewsJson/);
  assert.match(source, /buildCopyGroupHealthConcernSignature/);
  assert.match(source, /countRecentMatchingHealthReviews/);
  assert.match(source, /copyGroupHealthReviewFilter/);
  assert.match(source, /copyGroupHealthBoardView/);
  assert.match(source, /copyGroupHealthSearch/);
  assert.match(source, /selectedCopyGroupHealthGroupIds/);
  assert.match(source, /setCopyGroupHealthSearch/);
  assert.match(source, /setCopyGroupHealthReviewFilter/);
  assert.match(source, /setCopyGroupHealthBoardView/);
  assert.match(source, /staleCopyGroupHealthReviewCount/);
  assert.match(source, /unreviewedCopyGroupHealthCount/);
  assert.match(source, /recurringCopyGroupHealthCount/);
  assert.match(source, /filteredCopyGroupHealthEntries/);
  assert.match(source, /sortedCopyGroupHealthEntries/);
  assert.match(source, /handleAcknowledgeCopyGroupHealth/);
  assert.match(source, /handleClearCopyGroupHealthReview/);
  assert.match(source, /handleToggleCopyGroupHealthSelection/);
  assert.match(source, /handleSelectAllVisibleCopyGroupHealthEntries/);
  assert.match(source, /handleSelectStaleCopyGroupHealthEntries/);
  assert.match(source, /handleClearCopyGroupHealthSelection/);
  assert.match(source, /handleBulkClearCopyGroupHealthReviews/);
  assert.match(source, /handleBulkAcknowledgeCopyGroupHealthReviews/);
  assert.match(source, /leftReviewIsStale/);
  assert.match(source, /leftPriority/);
  assert.match(source, /Review stale/);
  assert.match(source, /Review needs refresh\./);
  assert.match(source, /repeatedReviewCount >= 2/);
  assert.match(source, /times in 24h/);
  assert.match(source, /Unreviewed \(/);
  assert.match(source, /Reviewed \(/);
  assert.match(source, /Stale Reviews \(/);
  assert.match(source, /Recurring \(/);
  assert.match(source, /Search groups, issues, notes, or reviewers/);
  assert.match(source, /COPY_GROUP_HEALTH_BOARD_VIEW_STORAGE_KEY/);
  assert.match(source, /loadStoredCopyGroupHealthBoardView/);
  assert.match(source, /normalizeCopyGroupHealthBoardView/);
  assert.match(source, /Compact view/);
  assert.match(source, /Detailed view/);
  assert.match(source, /Switch to detailed view for recovery context and review history\./);
  assert.match(source, /Select visible/);
  assert.match(source, /Select stale only/);
  assert.match(source, /Clear selection/);
  assert.match(source, /Re-acknowledge selected/);
  assert.match(source, /Clear selected reviews/);
  assert.match(source, /Select/);
  assert.match(source, /Operator note/);
  assert.match(source, /reviewedBy/);
  assert.match(source, /history/);
  assert.match(source, /Last touched by:/);
  assert.match(source, /Last reviewed at:/);
  assert.match(source, /Review Timeline/);
  assert.match(source, /Acknowledge/);
  assert.match(source, /Update review/);
  assert.match(source, /Clear review/);
  assert.match(source, /No copy groups match the current review filter right now\./);
  assert.match(source, /Risk Follow-Up/);
  assert.match(source, /Shared risk review queue/);
  assert.match(source, /Work breached, warning, and pending-risk accounts with shared ownership and review notes\./);
  assert.match(source, /riskFollowUpSearch/);
  assert.match(source, /riskFollowUpFilter/);
  assert.match(source, /filteredRiskFollowUpItems/);
  assert.match(source, /reviewedRiskFollowUpCount/);
  assert.match(source, /ownedRiskFollowUpCount/);
  assert.match(source, /unownedRiskFollowUpCount/);
  assert.match(source, /reassignedRiskFollowUpCount/);
  assert.match(source, /selectedRiskFollowUpAccountIds/);
  assert.match(source, /Search by account, issue, owner, or note/);
  assert.match(source, /Open \(/);
  assert.match(source, /Owned \(/);
  assert.match(source, /Unowned \(/);
  assert.match(source, /Reassigned \(/);
  assert.match(source, /Select visible/);
  assert.match(source, /Select unowned/);
  assert.match(source, /Clear selection/);
  assert.match(source, /Take ownership of selected/);
  assert.match(source, /Mark selected reviewed/);
  assert.match(source, /Reopen selected/);
  assert.match(source, /Reviewed at:/);
  assert.match(source, /Shared risk note/);
  assert.match(source, /Take ownership/);
  assert.match(source, /Save note/);
  assert.match(source, /Operator owner:/);
  assert.match(source, /Ownership Timeline/);
  assert.match(source, /No risk follow-up items match the current search right now\./);
  assert.match(source, /handleToggleRiskFollowUpSelection/);
  assert.match(source, /handleSelectAllVisibleRiskFollowUpItems/);
  assert.match(source, /handleSelectUnownedRiskFollowUpItems/);
  assert.match(source, /handleClearRiskFollowUpSelection/);
  assert.match(source, /handleBulkTakeRiskFollowUpOwnership/);
  assert.match(source, /handleBulkMarkRiskFollowUpReviewed/);
  assert.match(source, /handleBulkReopenRiskFollowUpItems/);
  assert.match(source, /handleTakeRiskFollowUpOwnership/);
  assert.match(source, /handleSaveRiskFollowUpNote/);
  assert.match(source, /handleMarkRiskFollowUpReviewed/);
  assert.match(source, /handleReopenRiskFollowUpItem/);
  assert.match(source, /saveRiskFollowUpReviewsMutation/);
  assert.match(source, /Operator Audit/);
  assert.match(source, /Manual sync ownership watchlist/);
  assert.match(source, /Overdue/);
  assert.match(source, /Unassigned/);
  assert.match(source, /Reassigned/);
  assert.match(source, /overdueSyncEntries/);
  assert.match(source, /unassignedSyncEntries/);
  assert.match(source, /reassignedSyncEntries/);
  assert.match(source, /queueAuditFocus/);
  assert.match(source, /queueSort/);
  assert.match(source, /normalizeQueueSort/);
  assert.match(source, /normalizeQueueAuditFocus/);
  assert.match(source, /ACTIVITY_QUEUE_SORT_STORAGE_KEY/);
  assert.match(source, /ACTIVITY_QUEUE_AUDIT_FOCUS_STORAGE_KEY/);
  assert.match(source, /window\.localStorage\.getItem/);
  assert.match(source, /window\.localStorage\.setItem/);
  assert.match(source, /activityPreferencesHydrated/);
  assert.match(source, /saveActivityPreferencesMutation/);
  assert.match(source, /apiRequest\("PATCH", "\/api\/user\/settings", settings\)/);
  assert.match(source, /activityQueueSort:\s*queueSort/);
  assert.match(source, /activityQueueAuditFocus:\s*queueAuditFocus/);
  assert.match(source, /copyGroupHealthReviewFilter/);
  assert.match(source, /copyGroupHealthReviewsJson/);
  assert.match(source, /queryClient\.setQueryData\(\["\/api\/auth\/me"\], result\)/);
  assert.match(source, /setQueueSort\(normalizeQueueSort\(user\.activityQueueSort\)\)/);
  assert.match(source, /setQueueAuditFocus\(normalizeQueueAuditFocus\(user\.activityQueueAuditFocus\)\)/);
  assert.match(source, /handleSelectAuditFocus/);
  assert.match(source, /auditFocusedQueue/);
  assert.match(source, /sortedAuditFocusedQueue/);
  assert.match(source, /Sync Review Queue/);
  assert.match(source, /Search by group, follower, note, or symbol/);
  assert.match(source, /Approve for manual execution/);
  assert.match(source, /Hand off for manual execution/);
  assert.match(source, /Mark completed manually/);
  assert.match(source, /Take ownership/);
  assert.match(source, /Newest/);
  assert.match(source, /Oldest First/);
  assert.match(source, /Reassignments/);
  assert.match(source, /Needs follow-up:/);
  assert.match(source, /Operator owner:/);
  assert.match(source, /Ownership changes:/);
  assert.match(source, /Latest ownership reason:/);
  assert.match(source, /Ownership Timeline/);
  assert.match(source, /Audit: Overdue/);
  assert.match(source, /Optional ownership reason/);
  assert.match(source, /operatorName: user\?\.username/);
});
