import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

test("notifications page surfaces the risk follow-up queue above the inbox list", () => {
  const source = readFileSync("client/src/pages/notifications.tsx", "utf8");

  assert.match(source, /RISK_FOLLOW_UP_REVIEWED_STORAGE_KEY/);
  assert.match(source, /loadReviewedRiskFollowUpItems/);
  assert.match(source, /reviewedRiskFollowUpItems/);
  assert.match(source, /reviewedRiskFollowUpCount/);
  assert.match(source, /parseRiskFollowUpReviewsJson/);
  assert.match(source, /useFollowUpReviewData/);
  assert.match(source, /useOperatorFollowUpData/);
  assert.match(source, /saveRiskFollowUpReviewsMutation/);
  assert.match(source, /saveRiskFollowUpPreferencesMutation/);
  assert.match(source, /riskFollowUpReviewsJson/);
  assert.match(source, /apiRequest\("PATCH", "\/api\/user\/settings", settings\)/);
  assert.match(source, /useFollowUpReviewActions/);
  assert.match(source, /buildRiskFollowUpReviewPayload/);
  assert.match(source, /riskFollowUpNotes/);
  assert.match(source, /NotificationsFollowUpPanels/);
  assert.match(source, /handleTakeOwnership/);
  assert.match(source, /handleSaveRiskFollowUpNote/);
  assert.match(source, /allRiskNotificationItems/);
  assert.match(source, /visibleRiskNotificationItems/);
  assert.match(source, /usePositionSyncReviewData/);
  assert.match(source, /summarizePositionSyncRepairCandidateQueue/);
  assert.match(source, /savePositionSyncWorkflowMutation/);
  assert.match(source, /usePositionSyncWorkflowActions/);
  assert.match(source, /buildPositionSyncWorkflowUpdate/);
  assert.match(source, /riskFollowUpItems/);
  assert.match(source, /syncRepairFollowUpItems/);
  assert.match(source, /handleTakeSyncRepairOwnership/);
  assert.match(source, /handleAdvanceSyncRepairCandidate/);
  assert.match(source, /handleMarkRiskFollowUpReviewed/);
  assert.match(source, /handleReopenRiskFollowUpItem/);
  assert.match(source, /"\/api\/runtime\/dashboard-overview"/);
  assert.match(source, /executionFollowUpItems/);
  assert.match(source, /reviewedExecutionFollowUpCount/);
  assert.match(source, /executionFollowUpSummary/);
  assert.match(source, /executionFollowUpNotes/);
  assert.match(source, /handleExecutionRecoveryRecheck/);
  assert.match(source, /handleExecutionRecoveryReview/);
  assert.match(source, /buildExecutionFollowUpReviewPayload/);
  assert.match(source, /handleTakeExecutionOwnership/);
  assert.match(source, /handleSaveExecutionFollowUpNote/);
  assert.match(source, /handleReopenExecutionFollowUpItem/);
  assert.match(source, /saveExecutionFollowUpReviewsMutation/);
  assert.match(source, /Restart recovery:/);
});
