import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

test("routes expose the authenticated runtime overview endpoints", () => {
  const routesSource = readFileSync("server/routes.ts", "utf8");

  assert.match(routesSource, /app\.get\("\/api\/runtime\/accounts-overview"/);
  assert.match(routesSource, /app\.get\("\/api\/position-sync\/plans"/);
  assert.match(routesSource, /app\.get\("\/api\/runtime\/dashboard-overview"/);
  assert.match(routesSource, /app\.post\("\/api\/runtime\/dashboard-overview\/recheck"/);
  assert.match(routesSource, /app\.post\("\/api\/runtime\/dashboard-overview\/recheck\/:historyId"/);
  assert.match(routesSource, /app\.post\("\/api\/runtime\/dashboard-overview\/review\/:historyId"/);
  assert.match(routesSource, /app\.get\("\/api\/execution-follow-up\/reviews"/);
  assert.match(routesSource, /app\.post\("\/api\/execution-follow-up\/reviews"/);
  assert.match(routesSource, /buildAccountsRuntimeOverview/);
  assert.match(routesSource, /buildDashboardRuntimeOverview/);
  assert.match(routesSource, /loadPositionSyncOverviewForUser/);
  assert.match(routesSource, /scope:\s*"position-sync-plans"/);
  assert.match(routesSource, /req\.query\.groupId/);
  assert.match(routesSource, /filterPositionSyncOverviewByGroupId/);
  assert.match(routesSource, /getOrCreateRuntimeSnapshot/);
  assert.match(routesSource, /clearRuntimeSnapshotCache/);
  assert.match(routesSource, /operationalLogger\.error\("runtime\.accounts_overview_load_failed"/);
  assert.match(routesSource, /operationalLogger\.error\("runtime\.position_sync_plans_load_failed"/);
  assert.match(routesSource, /message: "Failed to load accounts overview"/);
  assert.match(routesSource, /message: "Failed to load position sync plans"/);
  assert.match(routesSource, /operationalLogger\.error\("operations\.dashboard_overview_load_failed"/);
  assert.match(routesSource, /operationalLogger\.error\("operations\.dashboard_overview_recheck_failed"/);
  assert.match(routesSource, /operationalLogger\.error\("operations\.execution_follow_up_reviews_load_failed"/);
  assert.match(routesSource, /operationalLogger\.error\("operations\.execution_follow_up_reviews_save_failed"/);
  assert.match(routesSource, /operationalLogger\.error\("operations\.dashboard_recovery_recheck_failed"/);
  assert.match(routesSource, /operationalLogger\.error\("operations\.dashboard_recovery_review_failed"/);
  assert.match(routesSource, /message: "Failed to load dashboard overview"/);
  assert.match(routesSource, /message: "Failed to recheck dashboard overview"/);
  assert.match(routesSource, /message: "Failed to load execution follow-up reviews"/);
  assert.match(routesSource, /message: "Failed to save execution follow-up reviews"/);
  assert.match(routesSource, /message: "Failed to recheck dashboard recovery item"/);
  assert.match(routesSource, /message: "Failed to review dashboard recovery item"/);
});
