import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

test("activity copy-group health board keeps recovery controls and watchlist context together", () => {
  const source = readFileSync("client/src/components/activity-copy-group-health-board.tsx", "utf8");

  assert.match(source, /ActivityCopyGroupHealthBoard/);
  assert.match(source, /Copy Group Health/);
  assert.match(source, /Operational watchlist/);
  assert.match(source, /Needs Attention/);
  assert.match(source, /On Watch/);
  assert.match(source, /Stale Reviews/);
  assert.match(source, /Recurring Groups/);
  assert.match(source, /Followers Offline/);
  assert.match(source, /Recover Now Queue/);
  assert.match(source, /Focus Recover Now/);
  assert.match(source, /Select Recover Now/);
  assert.match(source, /Acknowledge selected urgent groups/);
  assert.match(source, /Clear selected urgent reviews/);
  assert.match(source, /Search groups, issues, notes, or reviewers/);
  assert.match(source, /Compact view/);
  assert.match(source, /Detailed view/);
  assert.match(source, /Select attention only/);
  assert.match(source, /Select stale only/);
  assert.match(source, /Re-acknowledge selected/);
  assert.match(source, /Clear selected reviews/);
  assert.match(source, /Review stale/);
  assert.match(source, /Review needs refresh\./);
  assert.match(source, /Next recovery step:/);
  assert.match(source, /Signal freshness/);
  assert.match(source, /getCopyGroupHealthSignalBadgeClass/);
  assert.match(source, /signalFreshnessTone/);
  assert.match(source, /signalFreshnessLabel/);
  assert.match(source, /signalFreshnessDetail/);
  assert.match(source, /routingGateTone/);
  assert.match(source, /routingGateLabel/);
  assert.match(source, /routingGateDetail/);
  assert.match(source, /Routing gate/);
  assert.match(source, /Restart recovery:/);
  assert.match(source, /Time in current warning state:/);
  assert.match(source, /Latest recovery action:/);
  assert.match(source, /Latest restart recovery:/);
  assert.match(source, /Review Timeline/);
  assert.match(source, /Operator note/);
  assert.match(source, /Update review/);
  assert.match(source, /Clear review/);
  assert.match(source, /No copy groups match the current review filter right now\./);
});
